name: Bug Report
description: Something isn’t working in OctaneRPG
title: "[Bug]: "
labels: ["type:bug", "needs:triage"]
body:
  - type: dropdown
    id: platform
    attributes:
      label: Where did this happen?
      options:
        - Discord bot
        - Web dashboard
        - API (developer)
        - Other / not sure
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - bot-commands
        - events
        - economy
        - vehicles
        - crew/guilds
        - inventory/items
        - admin/moderation
        - dashboard
        - api/backend
        - data/db
        - ux-copy
        - not sure
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the bug clearly.
      placeholder: "I used /race and it returned an error…"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: "It should have…"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Numbered steps are best.
      placeholder: |
        1. Run /command
        2. Choose X
        3. Observe Y
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / logs
      description: Paste screenshots or error text (remove personal info).
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity (your best guess)
      options:
        - cosmetic
        - minor
        - major
        - critical
    validations:
      required: true
